---
title: "droplet_size"
author: "Maxwel Coura Oliveira"
date: "8/24/2021"
output: html_document
---


```{r}
#load packages
library(tidyverse)
library(emmeans)
library(brms)
library(bayestestR)
library(modelbased)
library(ggtext)
library(patchwork)
library(ggrepel)
library(ggthemes)
library(extrafont)
library(showtext)
showtext_auto()
```


```{r}
#import dataset
readxl::read_excel("data/droplet_size_data.xlsx") %>% 
  janitor::clean_names() %>% 
  mutate(solution = str_replace_all(solution, "Intact", "DRA")) %>% 
  group_by(solution, nozzle) %>% 
  mutate(nozzle = str_remove_all(nozzle, '[0-9]+')) %>% 
  mutate(x200 = x200/100) %>% 
  mutate(rep = row_number()) -> droplet
```



 

```{r message = FALSE}
#dv10 model
model12 <- brm(`dv10` ~ solution ,
                  family = hurdle_gamma(link = "log", 
                                        link_shape = "log", 
                                        link_hu = "logit"),
               warmup = 1000, iter = 2000, chains = 4,
               prior = set_prior("student_t(0.5, 1, 2)", class = "b"),
                  data = droplet, save_pars = save_pars(all = TRUE))


model13 <- brm(`dv10` ~ solution * nozzle,
                  family = hurdle_gamma(link = "log", 
                                        link_shape = "log", 
                                        link_hu = "logit"),
               warmup = 1000, iter = 2000, chains = 4,
               prior = set_prior("student_t(0.5, 1, 2)", class = "b"),
                  data = droplet, save_pars = save_pars(all = TRUE))
```

```{r warning = FALSE, message = FALSE}
bayesfactor_models(model13, denominator = model12)
# There are extreme evidence for model13 (interaction)
```


```{r}
#dv10 comparison
dv10_main <- pairs(emmeans(model13, ~ nozzle * solution))

describe_posterior(dv10_main,
                   centrality = "mean", dispersion = TRUE,
                   ci = .95, ci_method = "hdi",
                   test = c("bayesfactor"),
                   bf_prior = model13)
```


```{r}
emmeans1 <- emmeans(model13, ~ nozzle * solution, 
                    cont="pairwise", type = "response")
```




```{r}
#dv50 model
model22 <- brm(`dv50` ~ solution,
                  family = hurdle_gamma(link = "log", 
                                        link_shape = "log", 
                                        link_hu = "logit"),
               warmup = 1000, iter = 2000, chains = 4,
               prior = set_prior("student_t(0.5, 1, 2)", class = "b"),
                  data = droplet, save_pars = save_pars(all = TRUE))


model23 <- brm(`dv50` ~ solution * nozzle,
                  family = hurdle_gamma(link = "log", 
                                        link_shape = "log", 
                                        link_hu = "logit"),
               warmup = 1000, iter = 2000, chains = 4,
               prior = set_prior("student_t(0.5, 1, 2)", class = "b"),
                  data = droplet, save_pars = save_pars(all = TRUE))
```

```{r}
bayesfactor_models(model23, denominator = model22)
# There are extreme evidence for model23 (interaction)
```


```{r}
emmeans2 <- emmeans(model23, ~ nozzle * solution, cont="pairwise", type = "response")
```


```{r}
#dv50 comparison
dv50_main <- pairs(emmeans(model23, ~ nozzle * solution))

describe_posterior(dv50_main,
                   centrality = "mean", dispersion = TRUE,
                   ci = .95, ci_method = "hdi",
                   test = c("bayesfactor"),
                   bf_prior = model23)
```





```{r}
#dv90 model
model32 <- brm(`dv90` ~ solution,
                  family = hurdle_gamma(link = "log", 
                                        link_shape = "log", 
                                        link_hu = "logit"),
               warmup = 1000, iter = 2000, chains = 4,
               prior = set_prior("student_t(0.5, 1, 2)", class = "b"),
                  data = droplet, save_pars = save_pars(all = TRUE))


model33 <- brm(`dv90` ~ solution * nozzle,
                  family = hurdle_gamma(link = "log", 
                                        link_shape = "log", 
                                        link_hu = "logit"),
               warmup = 1000, iter = 2000, chains = 4,
               prior = set_prior("student_t(0.5, 1, 2)", class = "b"),
                  data = droplet, save_pars = save_pars(all = TRUE))
```


```{r}
bayesfactor_models(model33, denominator = model32)
# There are extreme evidence for model33 (interaction)
```

```{r}
emmeans3 <- emmeans(model33, ~ nozzle * solution, cont="pairwise", type = "response")
```

```{r}
#dv90 comparison
dv90_main <- pairs(emmeans(model33, ~ nozzle * solution))

describe_posterior(dv90_main,
                   centrality = "mean", dispersion = TRUE,
                   ci = .95, ci_method = "hdi",
                   test = c("bayesfactor"),
                   bf_prior = model33)
```



```{r}
#relative spam
model42 <- brm(rs ~ solution,
                  family = hurdle_gamma(link = "log", 
                                        link_shape = "log", 
                                        link_hu = "logit"),
               warmup = 1000, iter = 2000, chains = 4,
               prior = set_prior("student_t(0.1, 0.5, 2)", 
                                 class = "b"),
                  data = droplet, save_pars = save_pars(all = TRUE))


model43 <- brm(rs ~ solution * nozzle,
                  family = hurdle_gamma(link = "log", 
                                        link_shape = "log", 
                                        link_hu = "logit"),
               warmup = 1000, iter = 2000, chains = 4,
               prior = set_prior("student_t(0.1, 0.5, 2)", 
                                 class = "b"),
                  data = droplet, save_pars = save_pars(all = TRUE))
```

```{r}
bayesfactor_models(model43, denominator = model42)
# There are extreme evidence for model42 (no interaction). We are going to present with interaction to keep all trt the same.
```

```{r}
emmeans4 <- emmeans(model43, ~ nozzle * solution, cont= "pairwise", type = "response")
```

```{r}
#relative spam comparison
rs_main <- pairs(emmeans(model43, ~ nozzle * solution))

describe_posterior(rs_main,
                   centrality = "mean", dispersion = TRUE,
                   ci = .95, ci_method = "hdi",
                   test = c("bayesfactor"),
                   bf_prior = model43)
```




```{r}
# drifable fines
model52 <- brm(`x200` ~ solution,
                  family = Beta(link = "logit", link_phi = "log"),
               warmup = 1000, iter = 2000, chains = 4,
               prior = set_prior("student_t(0.1, 0.5, 2)", 
                                 class = "b"),
                  data = droplet, save_pars = save_pars(all = TRUE))


model53 <- brm(`x200` ~ solution * nozzle,
                  family = Beta(link = "logit", link_phi = "log"),
               warmup = 1000, iter = 2000, chains = 4,
               prior = set_prior("student_t(0.1, 0.5, 2)", 
                                 class = "b"),
                  data = droplet, save_pars = save_pars(all = TRUE))
```

```{r}
bayesfactor_models(model53, denominator = model52)
# There are extreme evidence for model53 (interaction)
```

```{r}
emmeans5 <- emmeans(model53, ~ nozzle * solution, cont= "pairwise", type = "response")
```

```{r}
# drifable fines comparison
duz_main <- pairs(emmeans(model53, ~ nozzle * solution))

describe_posterior(duz_main,
                   centrality = "mean", dispersion = TRUE,
                   ci = .95, ci_method = "hdi",
                   test = c("bayesfactor"),
                   bf_prior = model53)
```



# Figures




```{r}
emmeans1$emmeans %>% as_tibble() %>% mutate(type = "DV10") -> em1
emmeans2$emmeans %>% as_tibble() %>% mutate(type = "DV50") -> em2
emmeans3$emmeans %>% as_tibble() %>% mutate(type = "DV90") -> em3
```

```{r}
em1 %>% 
  bind_rows(em2) %>% 
  bind_rows(em3) %>% 
  mutate(solution = str_replace(solution, "water", "")) %>% 
  unite("trt", c("solution", "nozzle"), sep = "-") %>% 
  mutate(trt = str_remove(trt, "^[^a-zA-Z]+")) %>%
  mutate(trt = str_remove(trt, "Water-")) %>% 
  mutate(type = fct_recode(type,
                          "D<sub>v10</sub>" = "DV10",
                          "D<sub>v50</sub>" = "DV50",
                          "D<sub>v90</sub>" = "DV90")) -> emm
```



```{r}
droplet %>% 
  pivot_longer(3:5, names_to = "type", values_to = "response") %>%
  mutate(type = str_to_upper(type)) %>% 
  unite("trt", c("solution", "nozzle"), sep = "-") %>% 
  mutate(trt = str_remove(trt, "^[^a-zA-Z]+")) %>%
  dplyr::select(-rs, -x200, -rep) %>% 
  mutate(trt = str_remove(trt, "Water-")) %>% 
  mutate(type = fct_recode(type,
                          "D<sub>v10</sub>" = "DV10",
                          "D<sub>v50</sub>" = "DV50",
                          "D<sub>v90</sub>" = "DV90")) -> droplet1
```


```{r}
emm %>% 
  mutate(response = round(response, 1)) %>% 
  ggplot(aes(x = fct_reorder(trt, response), 
             y = response, 
             color = trt, 
             shape = type)) +
  geom_linerange(aes(ymin = lower.HPD, ymax = upper.HPD),
                 position = position_dodge2(width = 0.4), 
                 size = 1.3, alpha = 0.5) +
  geom_point(size = 2, position = position_dodge2(width = 0.4)) +
  geom_jitter(data = droplet1,
                position = position_dodge2(width = 0.4),
              mapping = aes(color = trt, shape = type), alpha = 0.1, size = 2) +
  coord_flip() +
  geom_text_repel(aes(label = response, 
                         x = trt, color = trt, shape = type),
                    size = 8,
                    force_pull = 0,
                    direction = "y",
                    point.padding = NA,
                    min.segment.length = 14,
                    vjust = 0.5,
                    position = position_dodge2(width = 0.4),
                    seed = 455) +
  labs(x = NULL, y = "Droplet size (µm)", color = NULL, shape = NULL) +
  scale_color_viridis_d(option = "H") +
  scale_y_continuous(limits = c(0, 1500), breaks = seq(0, 1500, 300)) +
  scale_shape_manual(values = c(8,9,10)) +
  theme_few() + 
  theme(legend.position = c(0.85, 0.2),
        legend.text = element_markdown(size = 25),
        legend.margin = margin(0, 0, 0, 0),
        legend.spacing.x = unit(0, "mm"),
        legend.spacing.y = unit(0, "mm"),
        legend.background = element_blank(),
        axis.title = element_markdown(size = 30),
        axis.text = element_markdown(size = 25)) +
  guides(color = "none") -> fig1
```

                


```{r}
emmeans4$emmeans %>% as_tibble() %>% 
  mutate(solution = str_replace(solution, "Water", "")) %>% 
  unite("trt", c("solution", "nozzle"), sep = "-") %>% 
    mutate(trt = str_remove(trt, "^[^a-zA-Z]+")) -> em4
emmeans5$emmeans %>% as_tibble() -> em5
```


```{r}
droplet %>% 
  mutate(solution = str_replace(solution, "Water", "")) %>% 
  unite("trt", c("solution", "nozzle"), sep = "-") %>% 
  dplyr::select(trt, rs) %>% 
  mutate(trt = str_remove(trt, "^[^a-zA-Z]+")) %>%
  rename(response = rs) -> droplet2
```


```{r}
em4 %>% 
  mutate(response = round(response, 2)) %>% 
  ggplot(aes(x = fct_reorder(trt, response), y = response, color = trt)) +
  geom_linerange(aes(ymin = lower.HPD, ymax = upper.HPD),
                 position = position_dodge2(width = 0.4), 
                 size = 1.3, alpha = 0.5) +
  geom_point(size = 2, position = position_dodge2(width = 0.4)) +
  coord_flip() +
  geom_jitter(data = droplet2,
              mapping = aes(color = trt), alpha = 0.1, size = 2) +
  geom_text_repel(aes(label = response, 
                         x = trt),
                    size = 8,
                    force_pull = 0,
                    direction = "y",
                    point.padding = NA,
                    min.segment.length = 14,
                    vjust = 0.5,
                    position = position_dodge2(width = 0.4),
                    seed = 455) +
#  annotate("text", x = 5, y = 0.1, label = "There are differences \namong all pairwise trt  \ncomparisons (P <.0001) \nin figures A, B and C", size = 9, hjust = 0, lineheight = 0.3,
#           color = 1, fontface = "italic") +
  labs(x = NULL, y = "Relative span", color = NULL) +
  scale_color_viridis_d(option = "H") +
  scale_y_continuous(limits = c(0, 1.2), breaks = seq(0, 1.2, 0.2)) +
  theme_few() + 
  theme(legend.position = "none",
        axis.title = element_markdown(size = 30),
        axis.text = element_markdown(size = 25)) -> fig2
```



```{r}
emmeans5$emmeans %>% as_tibble() %>% 
  mutate(solution = str_replace(solution, "Water", "")) %>% 
  unite("trt", c("solution", "nozzle"), sep = "-") %>% 
  mutate(trt = str_remove(trt, "^[^a-zA-Z]+")) -> em5
```


```{r}
droplet %>% 
  mutate(solution = str_replace(solution, "Water", "")) %>% 
  unite("trt", c("solution", "nozzle"), sep = "-") %>% 
  dplyr::select(trt, x200) %>% 
  rename(response = x200) %>% 
  mutate(trt = str_remove(trt, "^[^a-zA-Z]+")) -> droplet3
```

```{r}
em5 %>% 
  mutate(response = round(response, 4)) %>% 
  ggplot(aes(x = fct_reorder(trt, response*100), y = response*100, color = trt)) +
  geom_linerange(aes(ymin = lower.HPD*100, ymax = upper.HPD*100),
                 position = position_dodge2(width = 0.4), 
                 size = 1.3, alpha = 0.5) +
  geom_point(size = 2, position = position_dodge2(width = 0.4)) +
  coord_flip() +
  geom_jitter(data = droplet2, 
              mapping = aes(color = trt), alpha = 0.1, size = 2) +
  geom_text_repel(aes(label = response*100, 
                         x = trt),
                    size = 8,
                    force_pull = 0,
                    direction = "y",
                    point.padding = NA,
                    min.segment.length = 14,
                    vjust = 0.5,
                    position = position_dodge2(width = 0.4),
                    seed = 455) +
#  annotate("text", x = 2, y = 3, label = "There are differences \namong all pairwise trt \ncomparisons (P <.0001)", size = 9, hjust = 0, lineheight = 0.3,
#           color = 1, fontface = "italic") +
  labs(x = NULL, y = "% driftable fines < 200 µm", color = NULL) +
  scale_color_viridis_d(option = "H") +
  scale_y_continuous(limits = c(0, 10), breaks = seq(0, 10, 2)) +
  theme_few() + 
  theme(legend.position = "none",
        axis.title = element_markdown(size = 30),
        axis.text = element_markdown(size = 25)) -> fig3
```




```{r warning = FALSE}
fig1 + fig2 + fig3 +
  plot_annotation(tag_levels = 'A') & 
  theme(plot.tag = element_text(size = 35, hjust = 0, vjust = 0))

ggsave("figures/Figure 1.png", width = 11, height = 4)
```
